name: releasing

on:
  push:
    branches:
      - release/major
      - release/minor
      - release/patch
      - release/premajor
      - release/preminor
      - release/prepatch
      - release/prerelease

jobs:
  releasing:
    name: releasing
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for OIDC
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Ensure npm 11.5.1 or later is installed for OIDC
        run: npm install -g npm@latest
      - id: npm-cache
        run: echo "dir=$(npm config get cache)" | tee -a "$GITHUB_OUTPUT"
      - id: npm-cache-restore
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - name: Set git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Versioning
        run: npm version "${GITHUB_REF##*/}"
      - name: Publish to npm
        run: npm publish
      - name: Push updates
        run: |
          git push origin ${{ github.ref_name }}
          git push origin --tags
      - name: Create Pull Request
        run: >
          gh pr create
          --base "${{ github.event.repository.default_branch }}"
          --body ''
          --head "${{ github.ref_name }}"
          --title "chore(release): publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
